### ISSUE TITLE
server side crashed

### ISSUE THREAD

**Issue by userid** [ccsexyz/tunnel#4]
The error message:

```
panic: runtime error: slice bounds out of range

goroutine 29 [running]:
main.(*FecConn).Write(0xc42007c4d0, 0xc4202f6f00, 0x4b0, 0x4b0, 0x4b0, 0x0, 0x0)
        C:/WhyGo/src/github.com/ccsexyz/tunnel/conn.go:140 +0x25c
github.com/ccsexyz/utils.PipeForUDPServer.func1(0x6b9540, 0xc42007c4d0, 0x6b9660, 0xc42000c758, 0xc4202dad80)
        C:/WhyGo/src/github.com/ccsexyz/utils/net.go:107 +0x189
created by github.com/ccsexyz/utils.PipeForUDPServer
        C:/WhyGo/src/github.com/ccsexyz/utils/net.go:111 +0x108
```

**Comment by ccsexyz** [comment]
try the newest release, it fixed some bugs about fec.
https://github.com/ccsexyz/tunnel/releases/tag/v20171111
